if [ -s /usr/local/etc/bash_completion.d ]; then
  for f in /usr/local/etc/bash_completion.d/*.bash; do source $f; done
fi

complete -o default -o nospace -F _git g

. ~/dotfiles/shell/functions
. ~/dotfiles/shell/aliases
. ~/dotfiles/shell/bash/colors
. ~/dotfiles/shell/bash/env

# bundle exec
[ -f ~/dotfiles/shell/bash/bundler-exec.sh ] && source ~/dotfiles/shell/bash/bundler-exec.sh
