call pathogen#infect()

syntax on
filetype plugin indent on

set nocompatible
set vb
set number
set showcmd
set nowrap
set list
set wildignore=.git,tmp,public/uploads
set noswapfile

colorscheme wombat256

"search
set hlsearch
set incsearch
set ignorecase
set smartcase

"indentation
set ts=2 sts=2 sw=2
set expandtab
set autoindent

" invisibles
set listchars=tab:▸\ ,eol:¬
set showbreak=…

highlight NonText     guifg=#4a4a59 ctermfg=238
highlight SpecialKey  guifg=#4a4a59 ctermfg=238

" statusline
set laststatus=2
set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)

if has('gui_macvim')
  set guifont=Menlo:h14
  set columns=160
  set linespace=2
  "let macvim_hig_shift_movement = 1
endif

" cursor change in insert mode
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" key mapping

let mapleader = ","
let g:CommandTCancelMap = ['<ESC>', '<C-c>']

nnoremap <Leader>w :w<CR>
nnoremap <Leader>cd :lcd %:h<CR>
nnoremap <Leader>rt :!bundle list --paths=true \| xargs ctags --extra=+f --exclude=.git --exclude=log -R *<CR><CR>
nnoremap <Leader>ve :edit $MYVIMRC<CR>
nnoremap <Leader>vs :source $MYVIMRC<CR>
nnoremap <Leader>p "0p<CR>
nnoremap <Leader>P "0P<CR>
nnoremap <Leader>t :CommandT<CR>
nnoremap <Leader>f :CommandTFlush<CR>\|:CommandT<CR>
nnoremap <F5> :GundoToggle<CR>
nnoremap <CR> :nohlsearch<CR>

if exists(":Tabularize")
  nmap <Leader>a= :Tabularize /=<CR>
  vmap <Leader>a= :Tabularize /=<CR>
  nmap <Leader>a: :Tabularize /:\zs<CR>
  vmap <Leader>a: :Tabularize /:\zs<CR>
endif

" For mac users (using the 'apple' key)
map <D-S-]> gt
map <D-S-[> gT
map <D-1> 1gt
map <D-2> 2gt
map <D-3> 3gt
map <D-4> 4gt
map <D-5> 5gt
map <D-6> 6gt
map <D-7> 7gt
map <D-8> 8gt
map <D-9> 9gt
map <D-0> :tablast<CR>

