# vim: set filetype=zsh :

export SHELL=`which zsh` # fix for the iterm2

source ~/dotfiles/shell.sh
source ~/dotfiles/shell/zsh/history.sh

setopt incappendhistory
setopt prompt_subst

autoload -Uz vcs_info
autoload -U compinit promptinit

compinit
promptinit

zstyle ':vcs_info:*' enable git svn
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' formats '%F{yellow}[%s:%b%u%c]%f '
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:*' unstagedstr '*'

precmd () { vcs_info }

export PROMPT='%B%(?..[%?] )%b%n %~ %F{yellow}${vcs_info_msg_0_}%f$ '
export RPROMPT="%F{green}%D{%L:%M}%f %F{blue}\$(show_ruby_version)%f"
